### ISSUE TITLE
CodeFlower

### ISSUE THREAD

**Issue by phodal** [inherd/coca#19]
**Describe the solution you'd like**

http://www.redotheweb.com/CodeFlower/

<img width="386" alt="image" src="https://user-images.githubusercontent.com/472311/97798778-34054500-1c64-11eb-81b6-d5c9688a7bb6.png">

**Comment by creasy2010** [comment]
how about this one 
@phodal 

```shell
# run this command . then generate  html to show the code Source code visualization
coca visual
# or 
coca report visual

```

**Comment by phodal** [comment]
@creasy2010 看上去不错，哈哈。不过 report 不合适

**Comment by phodal** [comment]
move to https://github.com/inherd/coco
